name: telco-churn-ci-ml
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools
          pip install -r requirements.txt

      - name: Run EDA script
        run: |
          python notebooks/01_EDA_Telco_Churn.py
      - name: Run Preprocessing script
        run: |
          python notebooks/02_Preprocessing_Telco_Churn.py
